import { Filter } from '@/components/Filter'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='border-b-2 px-4 py-2 '>
          <a href="/" className='font-bold' >DevJobs</a>
        </nav>
        <header className='mx-48'>
          <Filter />
        </header>
        {children}
      </body>
    </html>
  )
}
